<?php

namespace Modules\Mwz\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class MwzDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $now = DB::raw('NOW()');
        DB::statement("ALTER TABLE slugs AUTO_INCREMENT=1");
        DB::table('slugs')->truncate();
        DB::table('slugs')->insert(
            [
                [
                    'id' => 1,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'index-index-1',
                    'slug' => 'index',
                    'lang' => 'en',
                    'module' => 'index',
                    'method' => 'index',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 2,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'index-index-1',
                    'slug' => 'หน้าแรก',
                    'lang' => 'th',
                    'module' => 'index',
                    'method' => 'index',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 3,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'about-about-1',
                    'slug' => 'about',
                    'lang' => 'en',
                    'module' => 'about',
                    'method' => 'about',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 4,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'about-about-1',
                    'slug' => 'เกี่ยวกับเรา',
                    'lang' => 'th',
                    'module' => 'about',
                    'method' => 'about',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 5,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'product-product-1',
                    'slug' => 'product',
                    'lang' => 'en',
                    'module' => 'product',
                    'method' => 'product',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 6,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'product-product-1',
                    'slug' => 'รายการเบอร์มงคล',
                    'lang' => 'th',
                    'module' => 'product',
                    'method' => 'product',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 7,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'product-productDetail-1',
                    'slug' => 'productDetail',
                    'lang' => 'en',
                    'module' => 'product',
                    'method' => 'productDetail',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 8,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'product-productDetail-1',
                    'slug' => 'รายละเอียดสินค้า',
                    'lang' => 'th',
                    'module' => 'product',
                    'method' => 'productDetail',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [

                    'id' => 9,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'blog-blog-1',
                    'slug' => 'blog',
                    'lang' => 'en',
                    'module' => 'blog',
                    'method' => 'blog',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 10,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'blog-blog-1',
                    'slug' => 'ข่าวสารและกิจกรรม',
                    'lang' => 'th',
                    'module' => 'blog',
                    'method' => 'blog',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 11,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'blog-blogDetail-1',
                    'slug' => 'blogDetail',
                    'lang' => 'en',
                    'module' => 'blog',
                    'method' => 'blogDetail',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 12,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'blog-blogDetail-1',
                    'slug' => 'รายละเอียดข่าวสาร',
                    'lang' => 'th',
                    'module' => 'blog',
                    'method' => 'blogDetail',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 13,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'contact-contact-1',
                    'slug' => 'contact',
                    'lang' => 'en',
                    'module' => 'contact',
                    'method' => 'contact',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 14,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'contact-contact-1',
                    'slug' => 'ติดต่อเรา',
                    'lang' => 'th',
                    'module' => 'contact',
                    'method' => 'contact',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
              
                [
                    'id' => 15,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'policy-policy-1',
                    'slug' => 'policy',
                    'lang' => 'en',
                    'module' => 'policy',
                    'method' => 'policy',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                [
                    'id' => 16,
                    'type' => 1,
                    'level' => 1,
                    'slug_uid' => 'policy-policy-1',
                    'slug' => 'นโยบายความเป็นส่วนตัว',
                    'lang' => 'th',
                    'module' => 'policy',
                    'method' => 'policy',
                    'data_id' => 1,
                    'param' => '',
                    'meta_auther' => '',
                    'meta_title' => '',
                    'meta_keywords' => '',
                    'meta_description' => '',
                    'meta_image' => '',
                    'meta_robots' => '',
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
                
            ]
        );
    }
}
